.TH KSQUIRREL 1 "September 2005" "K Desktop Environment" "Image viewer for KDE"
.SH NAME
KSquirrel \- An image viewer for KDE with dynamic format support
.SH SYNOPSIS
.B ksquirrel
[\fIoptions\fR] [\fIfile\fR]
.SH DESCRIPTION
KSquirrel is an image viewer for KDE with disk navigator, file tree, thumbnails, extended thumbnails, dynamic format support, DCOP interface and KIPI plugins support.
.PP
Image loading is based on external codecs \- ksquirrel\-libs. It supports dozens of various image formats, including SVG, WMF, JPEG2000, APNG and PSD.
.SH OPTIONS
.SS Arguments:
.TP
.B file
An initial image file or folder.
.SS KSquirrel options:
.TP
.B  \-l
Show found image codecs and exit.
.TP
.B  \-d
Print available DCOP parameters.

.SS Generic options:
.TP
.B  \-\-help
Show help about options.
.TP
.B  \-\-help\-qt
Show Qt specific options.
.TP
.B  \-\-help\-kde
Show KDE specific options.
.TP
.B  \-\-help\-all
Show all options.
.TP
.B  \-\-author
Show author information.
.TP
.B \-v\fR, \fB\-\-version
Show version information.
.TP
.B  \-\-license
Show license information.
.TP
.B  \-\-
End of options.
.SH "SEE ALSO"
The KSquirrel homepage can be found at \fIhttp://ksquirrel.sourceforge.net\fR.
.SH BUGS
To report a bug, please send a e\-mail to \fIksquirrel.iv@gmail.com\fR.
.SH AUTHOR
KSquirrel and ksquirrel-libs were written by Dmitry Baryshev <ksquirrel.iv@gmail.com>.
.PP
This manual page was written by Dmitry Baryshev <ksquirrel.iv@gmail.com>.
